

- https://www.youtube.com/watch?v=7mkQi0TlJQo
- https://velog.io/@lky5697/suspense-in-different-architectures
- https://velog.io/@shinhw371/React-suspense-throw
- 목적과 쓰임
	- 코드 스플리팅 ? 
	- 비동기 상태와 에러 상태에 대해 선언적 처리 가능
	- React 18부터는 Server Component서포트하는 역할도 한다.

- [x] Suspense / ErrorBoundary 는 어떻게 자식의 상태를 알 수 있을까 ?
	- 처음접했을 때  `lazy(()=> import()); ` 형태를 Suspense로 감쌌던걸 기 억한다. 이것으로 추론을 해보면 컴포넌트가 Promise 를 Return하면 Suspense의 Fallback UI를 보여주는 것 같다.
	- 또,  우리가 return useQuery를 하지 않는데 어떻게 판단할까
	- 결국 => Suspense는 `throw Promise`를 캐치해서 자식의 상태를 알게되는 것  같다. 그래서 nested한 형태로 Suspense를 작성 할 수 있는 것이 아닌가
	
	- [x] `throw` 지시어의 동작 방식
 



# Throw의 동작방식
---
- 특징 : 제어권 이동 (즉 콜스택 제어), 매개변수 전달
- `throw`는 `Exception`이 아니라도 Object 기반의 객체면 모두 던질 수 있다.

1. **에러 발생:** 함수 실행 중에 `throw` 문을 통해 에러가 발생하면, 현재 실행 중인 코드의 실행이 중지됩니다.
2. **콜 스택 검사:** JavaScript 엔진은 현재 실행 컨텍스트에서 에러를 처리할 수 있는 `catch` 블록이 있는지 확인합니다. 현재 실행 컨텍스트 내에 적절한 `catch` 블록이 없으면, 해당 실행 컨텍스트는 콜 스택에서 제거(pop)됩니다.
3. **상위 실행 컨텍스트로 이동:** 제거된 실행 컨텍스트의 바로 위에 있는 상위 실행 컨텍스트가 현재 실행 컨텍스트가 됩니다. 엔진은 이 새로운 현재 실행 컨텍스트에서 `catch` 블록을 찾기 위해 동일한 검사를 반복합니다.
4. **`catch` 블록 발견:** 콜 스택을 거슬러 올라가는 도중 적절한 `catch` 블록을 발견하면, JavaScript 엔진은 에러를 해당 `catch` 블록으로 전달하고, 제어를 `catch` 블록으로 이동시킵니다. 이 때, `catch` 블록의 매개변수로 throw된  객체가 전달됩니다.
5. **처리되지 않은 에러:** 만약 콜 스택의 모든 실행 컨텍스트에서   `catch` 블록을 찾지 못하면, 에러는 처리되지 않은 에러(uncaught exception)로 남게 되며, 이는 보통 프로그램의 비정상 종료로 이어질 수 있습니다.

